### PR TITLE
DO NOT MERGE!: See how fast circle CI would run for -n 1 and what would fail

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Comment by yarikoptic** [comment]
hm, circle ci seems to not pick it up at all for some reason!

**Comment by satra** [comment]
it is running: https://circleci.com/gh/ReproNim/simple_workflow/84 - just not showing up here.

**Comment by yarikoptic** [comment]
but that isn't normal, right?

**Comment by yarikoptic** [comment]
was too long ago... closing

**Pull request closed without merging**
