### PR TITLE
BF: Added "anaconda" in environment.yml channels

### PR DESCRIPTION
**Pull request by eroesch**
The original channels are missing some packages.

### CODE REVIEW

**Comment by yarikoptic** [comment]
Do you remember what was missing? Last time I built it was probably over a year ago and it was fine. I just wondered if adding big mighty anaconda would eventually have a negative impact

**Comment by eroesch** [comment]
Yeah, I agree, and I hesitated too. Miniconda couldn't find the packages and/or versions. I looked them all up individually.
That said, that was the whole point of the simple workflow, to be able to replicate a given environment. If anaconda messes up, then that's really not the way forward. Failing that, a better non-container workflow would be to provide the entirety of the source packages in the repo.

ResolvePackageNotFound: 
  - lxml==3.6.1=py27_0
  - mkl==11.3.3=0
  - tk==8.5.18=0
  - readline==6.2=2
  - numpy==1.11.1=py27_0
  - libxslt==1.1.28=0
  - simplejson==3.8.2=py27_0
  - pyparsing==2.1.4=py27_0
  - scipy==0.18.0=np111py27_0

**Comment by satra** [comment]
@yarikoptic - what's being added here is the channel anaconda, not the entire set of packages that anaconda brings. 

i think conda removed it from being the default source.

**Comment by yarikoptic** [comment]
> @yarikoptic - what's being added here is the channel anaconda, not the entire set of packages that anaconda brings.

I understand that.  I just observed conda some times going frenzy trying to "satisfy the configuration" and adding additional channels contributes to it.

> i think conda removed it from being the default source.

I thought that conda/miniconda didn't have anaconda channel enabled by default.  I guess I was wrong in that and if it did before, then indeed adding `anaconda` here would be the right way to go.

A little archeological expedition:
https://anaconda.org/conda-forge/scipy/files?page=6 shows that there are 0.18.0-np111py27_ builds but they aren't `_0` and it was anaconda which provided that one: https://anaconda.org/anaconda/scipy/files?version=0.18.0 . 

So the fact that it worked is indeed probably that anaconda channel was enabled by default in miniconda and that changed.  Let's merge then!

**Pull request merged**
