### PR TITLE
ENH: prepare docker image using neurodebian snapshots

### PR DESCRIPTION
**Pull request by yarikoptic**
to build a docker image following "the recipe" but using jessie as it was some time in 2015 with FSL 5.0.9 (of some Debian revision):
    
    ./Simple_Prep_docker jessie 20150306T060524Z
    
 and then to execute actual analysis use
    
    docker run -it --rm repronim:simple_prep_yoh_jessie_20150306T060524Z /bin/bash -c '. setup_environment; cd simple_workflow-master && python run_demo_workflow.py --key 11an55u9t2TAf0EV2pHN0vOd8Ww2Gie-tHp9xGULh_dA && python check_output.py'

### CODE REVIEW

**Comment by satra** [comment]
yup source doesn't work directly, this is why we do this in many cases: https://github.com/BIDS-Apps/nipypelines/blob/master/Dockerfile#L12

**Comment by yarikoptic** [comment]
so for now we could stay with direct sourcing in the call -- listing/hardcoding all ENVs would not be possible for varying versions of FSL etc.  How do you like it otherwise? ;)

**Comment by satra** [comment]
it looks good for now.

next things are: 
- make `submit_output.sh` when output differs from expected output together with provenance
- create dashboard for comparing outputs
- use docker in circle to generate
- create multiple dockers (like nibotmi to go across OSes and FSL versions at least)
- represent the whole thing in NIDM-W

**Comment by yarikoptic** [comment]
ok then it is ready to be merged for now -- README.md documentation was tuned up to fit it in ;)

**Pull request merged**
